#Analyzing NanoString counts

##### Load in data and organize it #####

library(easypackages)
libraries("clusterProfiler", "ggplot2", "RColorBrewer", "org.Mm.eg.db", "ggbeeswarm")

#DESeq2 results generated by Dr. Robert Greenhalgh. Contact at robert.greenhalgh@utah.edu

dat <- read.csv("Nanostring_countsforR.csv") #whole dataset
datsum <- read.csv("DESeq/Nanostring_DeseqSummary.csv")
trans <- read.csv("Nanostring_transposed.csv")
trans$sum <- rowSums(trans[,8:833]) #Add all transcripts up.
trans$div_day <- factor(trans$div_day, levels=c('LO14', 'LO41', 'HI14', 'HI41'))
trans$microb <- factor(trans$microb, levels=c("LO", "HI"))
head(dat)
colnames(datsum)

trans14 <- trans[trans$day=="14",]
trans41 <- trans[trans$day=="41",]


##### Plot Nanostring counts #####
loimpcols <- c('#A11FE5', '#300049')
hiimpcols <- c("#DCAE1C" , "#644C00")
impcols <- c('#A11FE5', '#300049', "#DCAE1C" , "#644C00")

#Creating a boxplot of mRNA transcript counts
hist(trans$sum)
my_comparisons=list(c("HI14", "HI41"),  c("LO41", "HI14"), c("LO14", "HI41"), c("LO14", "HI14"),  
                    c("LO14", "LO41"))
pbox <- ggplot(trans, aes(x=div_day, y=sum)) +
  geom_boxplot(aes(colour=div_day), outlier.shape=NA) + 
  geom_beeswarm(aes(shape=div_day, color=div_day, fill=div_day), cex=4, size=3, alpha=0.9) +
  scale_colour_manual(values=c("#C66EF5","#460d63", "#FDD964","#644C00" )) +
  scale_fill_manual(values=c("#C66EF5", "#460d63", "#FDD964","#644C00")) +
  scale_shape_manual(values=c(16, 21, 15, 22)) +
  theme_bw() +
  theme(plot.title=element_text(size=14, face="bold"), 
        axis.title=element_text(size=14, face="bold"), 
        axis.text=element_text(size=11),
        legend.title=element_text(size=13, face="bold"), 
        legend.text=element_text(size=10)) + 
  labs(title="NanoString Expression totals",  
       fill= "Family", subtitle="", 
       x="Group",
       y="mRNA transcript count") +
  stat_compare_means(method="anova") +
  stat_compare_means(comparisons=my_comparisons) 
pbox

ggsave("~/Documents/1U4U_Nanostring/TranscriptsBoxplots.pdf" , pbox, units="in", height=7, width=5)



#Barplot
pbar <- ggplot(trans, aes(x=microb, y=sum)) +
  geom_bar(stat="identity", aes(fill=div_day)) + 
  scale_colour_manual(values=impcols) +
  scale_fill_manual(values=impcols) +
  # scale_shape_manual(values=c(21,21)) +
  #scale_color_manual(values=c("#000000", "#000000")) +
  ggtitle("NanoString Expression totals") +
  theme_bw() +
  theme(text=element_text(size=24), legend.position="none") +
  facet_wrap(~day, ncol = 2)
pbar



##### Analyze counts for differences across groups #####

wilcox.test(sum ~ microb, data=trans41)


##### Summarize data by group #####

summary(trans14$sum[trans14$microb=="LO"])
sd(trans14$sum[trans14$microb=="LO"])


#